id = "dataweave"
name = "DataWeave"
version = "0.0.1"
schema_version = 1
authors = ["Carlos Felipe Araújo"]
description = "DataWeave language support for Zed."
repository = "https://github.com/carlosxfelipe/zed-dataweave"

[grammars.dataweave]
repository = "https://github.com/carlosxfelipe/zed-dataweave"
rev = "50c809348b28b99d307b81e3bba34e4edad01d0a"
path = "tree-sitter-dataweave"
