id = "dataweave"
name = "DataWeave"
version = "0.0.1"
schema_version = 1
authors = ["Carlos Felipe Araújo"]
description = "DataWeave language support for Zed."
repository = "https://github.com/carlosxfelipe/zed-dataweave"

[grammars.dataweave]
repository = "https://github.com/carlosxfelipe/zed-dataweave"
rev = "de0c803a2f9f3292f3f62390f4075e3880eafd23"
path = "tree-sitter-dataweave"
